### PR TITLE
Make pathname-joining platform-independent (in particular so that it

### PR DESCRIPTION
**Pull request by alexthepineapple**
works on Unix with a '/' separator and Windows with a '\' separator).

### CODE REVIEW

**Comment by RabidSheep55** [comment]
Oh wow I wasn't aware in the difference in separators between linux and windows... Thanks for the fix!

**Comment by alexthepineapple** [comment]
On Fri, 24 Apr 2020, RabidSheep55 wrote:

> Oh wow I wasn't aware in the difference in separators between linux and windows... Thanks for the fix!

No problem!

I think there might be something wrong with your diamond spreading 
calculation.

Firstly, the diamond bonus should be calculated off the total action 
yield, but you are using a fixed multipler, namely 2. (E.g., line 38 of 
compareTypes.py). So for example Lapis minions make on average 6 base 
lapis per action and each one of these has a 0.1 chance of generating a 
diamond, so that should be on average 0.6 diamonds per action not 0.2.

Secondly, the diaBonus should be set to zero when 
curr["minionData"]["diamondSpreading"] is false, but what actually happens 
is that it remembers the diaBonus from the previous minion type.

Would you like me to submit another patch, or would you like to handle 
this?

Anyway, I was impressed with your calculations and graphs and your use of 
the API: it's very useful in optimising my minions. (My use case is that 
my 7 year old daughter plays and for some reason wants a Pigman sword. The 
method she was using would have taken about a year and required a lot of 
intervention. I now think I can do it in about two weeks with minimal 
intervention.)

(I have some other suggestions if you are interested, but maybe in another 
email.)

Alex

**Comment by RabidSheep55** [comment]
Thank you so much for this!

> diaBonus should be set to zero

The bug you mention here with diamond spreading breaks the whole script, thanks for pointing it out, I can't believe I missed it!!

>the diamond bonus should be calculated off the total action yield, but you are using a fixed multipler, namely 2

Yes! I thought diamond spreading would yield a diamond on 10% of the minions' total actions (so both the break and place action). This is why the multiplier was 2 here, as breaksPerH is the metric I use. Thank you so much for pointing that out, it does make a lot of sense, as snow minions were severly underestimated before.

I am working on implementing these fixes shortly, please feel free to give any suggestions to improve this!

**Comment by alexthepineapple** [comment]
Oh sorry, I thought I was sending the diamond-spreading email to you directly but github has cleverly made it part of the filename-joining pull request, so now two issues are mixed up. I don't think diamond spreading is quite right yet, but I'll open a new issue so that things are kept separate.

**Pull request merged**
